name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install composer deps and run phpunit
        run: |
          composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
          ./vendor/bin/phpunit --testsuite "Unit Test Suite"
