name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP with composer v1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          tools: composer:v1

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --prefer-dist

      - name: Run unit tests
        run: ./vendor/bin/phpunit --stderr --testsuite 'Unit Test Suite' --colors=always
